# Lecture 5: Building Tables
v.ekc

You've been *reading* tables, today you learn to **build** them: from scratch with arrays, and from files. Plus ranges, and one of the most famous datasets in the history of data visualization. (Slides: KL Lecture 05 deck.)

**Today's sections:**
1. Arrays recap
2. Columns of tables are arrays
3. Ranges
4. Ways to create a table
5. Print and string formatting

In [ ]:
from datascience import *
import numpy as np

---
## 1. Arrays Recap

Quick reps on arrays before we build with them. (Heads-up: one cell below errors **on purpose**, read the error message, it's a good one.)

In [ ]:
first_four = make_array(1, 2, 3, 4)

In [ ]:
first_four

Elementwise arithmetic, every element at once:

In [ ]:
first_four * 2

In [ ]:
first_four ** 2

In [ ]:
type(first_four)

Same-length arrays combine:

In [ ]:
next_four = make_array(5, 6, 7, 8)

In [ ]:
first_four + next_four

Mismatched lengths: here's the promised on-purpose error:

In [ ]:
only_three = make_array(5, 6, 7)

In [ ]:
# This line will cause an error 
first_four + only_three

Familiar functions work on arrays, and the array itself never changes:

In [ ]:
min(first_four)

In [ ]:
first_four # array is unchanged, just like when we call show/select/drop on Table

Strings ride along too, but watch what *mixing* types does:

In [ ]:
str_array = make_array('ha', 'he', 'ho')

In [ ]:
# Check the number of elements
len(str_array)

Mix in a float or a string and **everything** converts:

In [ ]:
make_array(1.0,2,3)

In [ ]:
make_array('ha',2,3)

Single elements come out with `.item`, zero-indexed, and negatives count from the end:

In [ ]:
first_four.item(0)

In [ ]:
first_four.item(1)

In [ ]:
# Select the last item
first_four.item(-1)

Totals and averages:

In [ ]:
sum(first_four)

In [ ]:
np.average(first_four)

### Try It 1: Even average 😊

1. What is the average of all *even* numbers between 2 and 16 (inclusive)?

In [ ]:
# 1. average of evens from 2 to 16

<details>
<summary>💡 Possible answers — click to peek</summary>
<br>

*You could type them all out, or let `np.arange` do it (next section shows why the stop is 17).*

```python
# 1.
np.average(make_array(2, 4, 6, 8, 10, 12, 14, 16))
# or, sneak preview:
np.average(np.arange(2, 17, 2))
```

</details>

---
## 2. Ranges

`np.arange` builds evenly spaced arrays so you don't have to type them out.

### 📋 Reference Table

| Code | Result |
|---|---|
| `np.arange(7)` | 0, 1, 2, 3, 4, 5, 6 |
| `np.arange(5, 11)` | 5, 6, 7, 8, 9, 10 |
| `np.arange(0, 20, 2)` | 0, 2, …, 18 — the stop is **not** included! |

In [ ]:
make_array(0, 1, 2, 3, 4, 5, 6)

In [ ]:
np.arange(7)

Start, stop, and the stop **never** makes the cut:

In [ ]:
np.arange(5, 11)

In [ ]:
np.arange(0, 20, 2)

Off-by-one insurance: to include 20, stop at 21. Steps can even be decimals:

In [ ]:
np.arange(0, 21, 2)

In [ ]:
np.arange(0, 1, 0.1)

### Try It 3: Odd count 😊

1. How many odd numbers are there between 5 and 75 (inclusive)? *Hint: create the relevant array, then apply a function that tells you how many elements it has.*

In [ ]:
# 1. how many odds from 5 to 75

<details>
<summary>💡 Possible answers — click to peek</summary>
<br>

*The stop is 76 because `np.arange` never includes it.*

```python
# 1.
len(np.arange(5, 76, 2))
```

</details>

---
## 3. Columns of Tables are Arrays

Back to the NBA, this time paying attention to what each operation *returns*.

### 📋 Reference Table

| Code | What it does |
|---|---|
| `t.num_rows`, `t.num_columns` | table dimensions (no parentheses!) |
| `t.labels` | the column names |
| `t.relabeled('old', 'new')` | new table with a renamed column |
| `t.select('A')` | one-column **Table** |
| `t.column('A')` | that column as an **array** |
| `t.take(0)` | new table containing just row 0 |

In [ ]:
nba = Table.read_table('nba_salaries.csv').where('season', 2020).drop('season')
nba.show(5)

Three quick facts about any table: rows, columns, labels:

In [ ]:
nba.num_rows

In [ ]:
nba.num_columns

In [ ]:
nba.labels

Filter to one team, and rename a column on the way:

In [ ]:
warriors = nba.where('team', 'Golden State Warriors')
warriors.show(5)

In [ ]:
warriors.relabeled('salary', '$')

`relabeled` handed back a *new* table: `warriors` didn't change. Chain it all and reassign:

In [ ]:
warriors

In [ ]:
warriors = nba.where('team', 'Golden State Warriors').drop('team').relabeled('salary', '$')
warriors.show(3)

`select` vs `column`, round two: error included on purpose:

In [ ]:
warriors.select('$')

In [ ]:
type(warriors.select('$'))

In [ ]:
# This will produce an error
np.average(warriors.select('$'))

…and the version that works:

In [ ]:
warriors.column('$')

In [ ]:
type(warriors.column('$'))

In [ ]:
np.average(warriors.column('$'))

> **Worth repeating:** `.select` → Table, `.column` → array. The error two cells up is what happens when you hand `np.average` a Table. 😬

In [ ]:
# another way
warriors.column(3)

Head-to-head comparison, average, then total:

In [ ]:
suns = nba.where('team', 'Phoenix Suns').drop('team').relabeled('salary', '$')

In [ ]:
np.average(warriors.column('$')) > np.average(suns.column('$'))

In [ ]:
np.sum(warriors.column('$')) > np.sum(suns.column('$'))

### Try It 2: Warriors rank 😊

1. What was the average **rank** of players on the Golden State Warriors in 2020?

In [ ]:
# 1. average rank of the Warriors in 2020

<details>
<summary>💡 Possible answers — click to peek</summary>
<br>

*Same pattern as salaries, grab the column as an array, then average it.*

```python
# 1.
np.average(warriors.column('rank'))
```

</details>

In [ ]:
# A note about taking rows
nba.take(0)

---
## 4. Ways to Create a Table

Two ways: build from arrays with `Table().with_columns(...)`, or read a file with `Table.read_table(...)`. From scratch first, the streets south of campus:

In [15]:
streets = make_array('14th', '13th', '12th', '11th')
streets

array(['14th', '13th', '12th', '11th'],
      dtype='<U4')

In [16]:
Table()

Add a column and it's a real table:

In [18]:
# instantiate the empty Table()

southside = Table().with_column('Streets', streets)
southside

Streets
14th
13th
12th
11th

In [19]:
southside.with_column('Blocks from campus', np.arange(4))

Streets | Blocks from campus
14th    | 0
13th    | 1
12th    | 2
11th    | 3

In [ ]:
southside

Name the result to keep it, then the two-column shortcut:

In [ ]:
southside = southside.with_column('Blocks from campus', np.arange(4))
southside

In [20]:
Table().with_columns(
    'Streets', streets,
    'Blocks from campus', np.arange(4)
)

Streets | Blocks from campus
14th    | 0
13th    | 1
12th    | 2
11th    | 3

### Reading a Table from a File

> **About this dataset:** W. E. B. Du Bois assembled these income and expenditure data on Black families in Atlanta for the 1900 Paris Exposition, alongside hand-drawn charts that remain some of the most celebrated visualizations ever made. (KL deck, slide 13.) Each row is an income bracket; the expense columns are *proportions* of income.

In [21]:
du_bois = Table.read_table('du_bois.csv')
du_bois

CLASS         | ACTUAL AVERAGE | RENT | FOOD | CLOTHES | TAXES | OTHER | STATUS
100-200       | 139.1          | 0.19 | 0.43 | 0.28    | 0.001 | 0.099 | POOR
200-300       | 249.45         | 0.22 | 0.47 | 0.23    | 0.04  | 0.04  | POOR
300-400       | 335.66         | 0.23 | 0.43 | 0.18    | 0.045 | 0.115 | FAIR
400-500       | 433.82         | 0.18 | 0.37 | 0.15    | 0.055 | 0.245 | FAIR
500-750       | 547            | 0.13 | 0.31 | 0.17    | 0.05  | 0.34  | COMFORTABLE
750-1000      | 880            | 0    | 0.37 | 0.19    | 0.08  | 0.36  | COMFORTABLE
1000 and over | 1125           | 0    | 0.29 | 0.16    | 0.045 | 0.505 | WELL-TO-DO

In [ ]:
du_bois.column('ACTUAL AVERAGE')

In [ ]:
du_bois.column('FOOD')

Proportions × income = dollars; compute it, then attach it as a new column:

In [ ]:
du_bois.column('ACTUAL AVERAGE') * du_bois.column('FOOD')

In [22]:
food_dollars = du_bois.column('ACTUAL AVERAGE') * du_bois.column('FOOD')
du_bois.with_column('Food $', food_dollars)

CLASS         | ACTUAL AVERAGE | RENT | FOOD | CLOTHES | TAXES | OTHER | STATUS      | Food $
100-200       | 139.1          | 0.19 | 0.43 | 0.28    | 0.001 | 0.099 | POOR        | 59.813
200-300       | 249.45         | 0.22 | 0.47 | 0.23    | 0.04  | 0.04  | POOR        | 117.241
300-400       | 335.66         | 0.23 | 0.43 | 0.18    | 0.045 | 0.115 | FAIR        | 144.334
400-500       | 433.82         | 0.18 | 0.37 | 0.15    | 0.055 | 0.245 | FAIR        | 160.513
500-750       | 547            | 0.13 | 0.31 | 0.17    | 0.05  | 0.34  | COMFORTABLE | 169.57
750-1000      | 880            | 0    | 0.37 | 0.19    | 0.08  | 0.36  | COMFORTABLE | 325.6
1000 and over | 1125           | 0    | 0.29 | 0.16    | 0.045 | 0.505 | WELL-TO-DO  | 326.25

In [23]:
du_bois = du_bois.with_column('Food $', food_dollars)
du_bois

CLASS         | ACTUAL AVERAGE | RENT | FOOD | CLOTHES | TAXES | OTHER | STATUS      | Food $
100-200       | 139.1          | 0.19 | 0.43 | 0.28    | 0.001 | 0.099 | POOR        | 59.813
200-300       | 249.45         | 0.22 | 0.47 | 0.23    | 0.04  | 0.04  | POOR        | 117.241
300-400       | 335.66         | 0.23 | 0.43 | 0.18    | 0.045 | 0.115 | FAIR        | 144.334
400-500       | 433.82         | 0.18 | 0.37 | 0.15    | 0.055 | 0.245 | FAIR        | 160.513
500-750       | 547            | 0.13 | 0.31 | 0.17    | 0.05  | 0.34  | COMFORTABLE | 169.57
750-1000      | 880            | 0    | 0.37 | 0.19    | 0.08  | 0.36  | COMFORTABLE | 325.6
1000 and over | 1125           | 0    | 0.29 | 0.16    | 0.045 | 0.505 | WELL-TO-DO  | 326.25

Who spent the most of their income on rent, and how does everyone compare to them?

In [26]:
# we can find the max rent with np.max
np.max(du_bois.column('RENT'))

0.23000000000000001

In [29]:
# how to calculate which GROUP had the highest RENT percent
du_bois.sort('RENT', descending=False).column('CLASS').item(0)

'750-1000'

### Try It 4: Du Bois 😊

1. Use the table functions we learned this week to find the income bracket (`CLASS`) that spent the **highest proportion of income on rent**.

In [ ]:
# 1. class with highest rent proportion

<details>
<summary>💡 Possible answers — click to peek</summary>
<br>

*Sort by rent, then pull the top row's class (`.column` + `.item(0)` also works).*

```python
# 1.
du_bois.sort('RENT', descending=True).column('CLASS').item(0)
```

</details>

### One more `where` trick

`are.containing` matches partial text, handy when categories share letters:

In [ ]:
nba.where('position', are.containing('G'))

---
## 5. Print and String Formatting

One quiet mystery, solved: notebooks only display the *last* expression in a cell. `print` shows whatever you want, whenever you want, and f-strings let you drop values into text.

In [ ]:
1 + 2
3 + 4

In [ ]:
print(1 + 2)
print(3 + 4)

In [ ]:
'Go Humboldt!'

In [ ]:
print('Go Humboldt!')

**f-strings**: prefix with `f` and `{}` pulls in live values:

In [ ]:
cph = 'Cal Poly Humboldt'

In [ ]:
'{cph} is awesome'

Without the `f`, braces are just braces. Add it:

In [ ]:
f'{cph} is awesome'

In [ ]:
print(f'{cph} is awesome!')
print(f'{warriors.column("name").item(0)} is pretty awesome too!')

### Try It 5: Your own f-string 😊

1. Store your name and your favorite number in two names, then use an f-string to print `"<name>'s favorite number is <number>"`.

2. Bonus: print the Warriors' **highest** salary with a label, pulling the value straight from the table.

In [ ]:
# 1. your f-string

In [ ]:
# 2. bonus: top Warriors salary, labeled

<details>
<summary>💡 Possible answers — click to peek</summary>
<br>

*Anything in the `{}` is live Python: names, expressions, even table lookups.*

```python
# 1.
name = 'Gus'
fav = 8
print(f"{name}'s favorite number is {fav}")

# 2.
print(f'Top Warriors salary: {np.max(warriors.column("$"))}')
```

</details>

---
> **Today's takeaway:** arrays build columns, columns build tables, and now you can make tables from scratch, not just read them. Homework 2 uses every trick on this page.

## Appendix — Quick Reference

Full `datascience` docs: [data8.org/datascience](https://data8.org/datascience/)

### Minimal template — build a table from arrays
```python
t = Table().with_columns(
    'Label A', array_a,
    'Label B', array_b)
```